#!/usr/bin/env bash
#
# stamp-provenance.sh — regenerate src/PROVENANCE.toml against the current
# git history. Run before tagging a new release. Idempotent: re-running on
# the same commit produces the same file.
#
# Usage:
#   scripts/stamp-provenance.sh <next-version-tag>
#
#     Example: scripts/stamp-provenance.sh v0.5.0
#
#   The script walks every file under src/ (excluding PROVENANCE.toml itself),
#   asks git for the most recent tag in which the file changed, and writes
#   the mapping. Files modified since the last tag are stamped with
#   <next-version-tag> (the version that's about to ship).
#
#   --seed <tag>     Use the given tag as the seed-version for files whose
#                    git history pre-dates PROVENANCE.toml. Used for the
#                    initial v0.4.0 generation.
#
#   --check          Compare against the existing PROVENANCE.toml and exit
#                    nonzero if regeneration would change anything (use as a
#                    pre-tag CI check).
#
# Conventions:
#   - The script must be run from the processkit repo root.
#   - The git working tree should be clean (uncommitted changes will affect
#     the result; the script warns).
#   - The output is written to src/PROVENANCE.toml. Commit it before tagging.
#
# Output format:
#   See src/PROVENANCE.toml for the schema. Two top-level tables:
#   [source] (project name, upstream URL, generated_at, generated_for_tag)
#   [files] (path → version)
#
# This script is the upstream / consumer-neutral implementation. Forks who
# rebrand their project should:
#   - update [source].project in PROVENANCE.toml (one-time)
#   - regenerate against THEIR fork's git history (use this script verbatim)
#   - keep their own [source].upstream URL

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$REPO_ROOT" ]]; then
    echo "Error: not inside a git repository" >&2
    exit 1
fi
cd "$REPO_ROOT"

SRC_DIR="src"
PROVENANCE_FILE="$SRC_DIR/PROVENANCE.toml"
NEXT_VERSION=""
SEED_VERSION=""
CHECK_MODE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --seed)
            SEED_VERSION="$2"
            shift 2
            ;;
        --check)
            CHECK_MODE=1
            shift
            ;;
        -h|--help)
            sed -n '3,40p' "$0" | sed 's/^# *//'
            exit 0
            ;;
        v[0-9]*)
            NEXT_VERSION="$1"
            shift
            ;;
        *)
            echo "Error: unknown argument '$1'" >&2
            echo "Run with --help for usage." >&2
            exit 2
            ;;
    esac
done

if [[ -z "$NEXT_VERSION" && -z "$SEED_VERSION" ]]; then
    echo "Error: must specify <next-version-tag> (e.g. v0.5.0)" >&2
    echo "Run with --help for usage." >&2
    exit 2
fi

EFFECTIVE_VERSION="${NEXT_VERSION:-$SEED_VERSION}"

# Sanity: warn if working tree is dirty
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "Warning: working tree is not clean. Stamped versions may differ from" >&2
    echo "         what gets tagged. Commit your changes first." >&2
fi

# Read the upstream URL from the existing file if present, else default to upstream
UPSTREAM_URL="https://github.com/projectious-work/processkit.git"
PROJECT_NAME="processkit"
if [[ -f "$PROVENANCE_FILE" ]]; then
    existing_url=$(awk '/^upstream/ {gsub(/[" ]/, "", $3); print $3; exit}' "$PROVENANCE_FILE" 2>/dev/null || true)
    [[ -n "$existing_url" ]] && UPSTREAM_URL="$existing_url"
    existing_project=$(awk '/^project/ {gsub(/[" ]/, "", $3); print $3; exit}' "$PROVENANCE_FILE" 2>/dev/null || true)
    [[ -n "$existing_project" ]] && PROJECT_NAME="$existing_project"
fi

# Build the new file in a temp location, then atomically replace.
TMP_FILE=$(mktemp)
trap 'rm -f "$TMP_FILE"' EXIT

GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$TMP_FILE" <<EOF
# PROVENANCE.toml — file-to-version provenance map
#
# Auto-generated by scripts/stamp-provenance.sh — do not edit by hand.
# Maps every file shipped under src/ to the tag in which it last changed.
# Consumed by scripts/processkit-diff.sh and by aibox sync.

[source]
project = "$PROJECT_NAME"
upstream = "$UPSTREAM_URL"
generated_at = "$GENERATED_AT"
generated_for_tag = "$EFFECTIVE_VERSION"

[files]
EOF

# For each file under src/, find the most recent tag that touched it.
# We use git log --tags -1 --format=%D <file> to get the decoration list,
# then parse out the most recent tag name. If the file has uncommitted
# changes (or has changed since the last tag), we use $EFFECTIVE_VERSION.

# Get the list of files (sorted, excluding PROVENANCE.toml itself)
mapfile -t FILES < <(
    find "$SRC_DIR" -type f \
        ! -path "$PROVENANCE_FILE" \
        ! -name '*.pyc' \
        ! -path '*/__pycache__/*' \
        | sort
)

for f in "${FILES[@]}"; do
    rel="${f#$SRC_DIR/}"

    # Find the most recent commit that touched this file.
    # Then find the closest tag (reachable from that commit) that contains it.
    last_commit=$(git log -1 --format=%H -- "$f" 2>/dev/null || echo "")
    if [[ -z "$last_commit" ]]; then
        # File is new (not yet committed)
        version="$EFFECTIVE_VERSION"
    else
        # Find the earliest tag that contains this commit
        # (--contains lists tags reachable FROM the commit; we want the oldest)
        version=$(git tag --contains "$last_commit" --sort=v:refname 2>/dev/null \
                  | grep '^v[0-9]' | head -1 || true)
        if [[ -z "$version" ]]; then
            # Commit is not in any tagged release yet — use the effective version
            version="$EFFECTIVE_VERSION"
        fi
    fi

    printf '"%s" = "%s"\n' "$rel" "$version" >> "$TMP_FILE"
done

if [[ "$CHECK_MODE" -eq 1 ]]; then
    if ! diff -q "$PROVENANCE_FILE" "$TMP_FILE" >/dev/null 2>&1; then
        echo "PROVENANCE.toml is out of date. Regenerate with:" >&2
        echo "  scripts/stamp-provenance.sh $EFFECTIVE_VERSION" >&2
        exit 3
    fi
    echo "PROVENANCE.toml is up to date."
    exit 0
fi

mv "$TMP_FILE" "$PROVENANCE_FILE"
echo "Wrote $PROVENANCE_FILE for $EFFECTIVE_VERSION (${#FILES[@]} files)."
echo "Review with: git diff $PROVENANCE_FILE"
